config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :restaurants


  # creer un restaurant
  # get 'restaurants/new', to: "restaurants#new"
  # post 'restaurants/create', to: "restaurants#create"


  # lire tous les restaurants
  # get 'restaurants', to: "restaurants#index"

  # lire un restaurant
  # get 'restaurants/:id', to: "restaurants#show"


  # updater un restaurant
  # get 'restaurants/:id/edit', to: "restaurants#edit"
  # patch 'restaurants/:id', to: "restaurants#update"

  # supprimer un restaurant
  # delete 'restaurants/:id', to: "restaurants#destroy"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :star,  presence: true
  validates :star, numericality: { less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_restaurant, only: [:show, :edit, :update, :destroy ]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end


  def edit
    # recupere le resto à éditer
    # affiche le formulaire
  end

  def update
    # recupere le resto
    # update les params
    @restaurant.update(restaurant_params)
    # je sauve
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :edit
    end
  end

  def destroy
    # on recupere le resto
    # On le destroy
    @restaurant.destroy
    # on redirect vers la liste
    redirect_to restaurants_path
  end


  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :star)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lafourchette37</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :address %>
  <%= f.number_field :star %>
  <%= f.submit "Valider" %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editer un restaurant</h1>


<%= render partial: 'form' %>

app/views/restaurants/index.html.erb
<h1>Tous les restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
  <li>
    <h2><%= restaurant.name %></h2>
    <p><%= restaurant.address %></p>
    <p><%= restaurant.star %></p>
    <p>
      <%= link_to "Details", restaurant_path(restaurant.id)%>
    </p>
  </li>
  <% end %>
</ul>

<%= link_to "Ajouter un restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Création d'un restaurant</h1>


<%= render partial: 'form' %>

app/views/restaurants/show.html.erb
<h1>Restaurant : <%= @restaurant.name %></h1>

<p><%= @restaurant.address %></p>
<p><%= @restaurant.star %></p>


<p>
  <%= link_to "Back Home", restaurants_path %>
  <%= link_to "Update", edit_restaurant_path(@restaurant) %>
  <%= link_to "Delete", restaurant_path(@restaurant), method: "DELETE" %>

</p>